version: '3.3'
services:
    samsung_legacy_aircon_connector:
        restart: always
        ports:
            - '20080:20080'
        container_name: samsung_aircon_connector
        volumes:
            - '/volume1/docker/samsung_aircon_connector/config:/config:cached'
        image: zambobmaz/samsung_aircon_connector
