version: '3.3'
services:
    samsung_legacy_aircon_connector:
        restart: always
        ports:
            - '20080:20080'
        container_name: samsung_aircon_connector
        volumes:
            - '/your/host/directory/config:/config:cached:/config'
        image: zambobmaz/samsung_legacy_aircon_connector
