---
dashboard:
  states:
  - label: "{{acVolume.value}}"
  actions: []
  basicPlus: []
detailView:
- label: 음량
  displayType: list
  list:
    command:
      name: setAcVolume
      alternatives:
      - key: Mute
        value: 음소거
      - key: '33'
        value: 작게
      - key: '66'
        value: 보통
      - key: '100'
        value: 크게
      supportedValues: supportedAcVolumes.value
    state:
      value: acVolume.value
      alternatives:
      - key: Mute
        value: 음소거
      - key: '33'
        value: 작게
      - key: '66'
        value: 보통
      - key: '100'
        value: 크게
automation:
  conditions:
  - label: 음량
    displayType: list
    list:
      value: acVolume.value
      alternatives:
      - key: Mute
        value: 음소거
      - key: '33'
        value: 작게
      - key: '66'
        value: 보통
      - key: '100'
        value: 크게
  actions:
  - label: 음량
    displayType: list
    list:
      command: setAcVolume
      alternatives:
      - key: Mute
        value: 음소거
      - key: '33'
        value: 작게
      - key: '66'
        value: 보통
      - key: '100'
        value: 크게
      supportedValues: supportedAcVolumes.value
id: imageafter45121.acVolume
version: 1
