dashboard:
  states:
    - component: main
      capability: temperatureMeasurement
      version: 1
      values: []
  actions:
    - component: main
      capability: switch
      version: 1
  basicPlus: []
detailView:
  - component: main
    capability: temperatureMeasurement
    version: 1
    values: []
    patch: []
  - component: main
    capability: switch
    version: 1
    values: []
    patch: []
  - component: main
    capability: refresh
    version: 1
    values: []
    patch: []
  - component: main
    capability: imageafter45121.acTempSet
    version: 1
    values: []
    patch: []
  - component: main
    capability: imageafter45121.acWindLevel
    version: 1
    values: []
    patch: []
  - component: main
    capability: imageafter45121.acOpMode
    version: 1
    values: []
    patch: []
  - component: main
    capability: imageafter45121.acVolume
    version: 1
    values: []
    patch: []
  - component: main
    capability: imageafter45121.acOperation
    version: 1
    values: []
    patch: []
  - component: main
    capability: imageafter45121.acDirection
    version: 1
    values: []
    patch: []
  - component: main
    capability: imageafter45121.acCoMode
    version: 1
    values: []
    patch: []
  - component: main
    capability: imageafter45121.acAutoClean
    version: 1
    values: []
    patch: []
automation:
  conditions:
    - component: main
      capability: temperatureMeasurement
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main
      capability: switch
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main
      capability: refresh
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main
      capability: imageafter45121.acTempSet
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main
      capability: imageafter45121.acWindLevel
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main
      capability: imageafter45121.acOpMode
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main
      capability: imageafter45121.acVolume
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main
      capability: imageafter45121.acOperation
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main
      capability: imageafter45121.acDirection
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main
      capability: imageafter45121.acCoMode
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main
      capability: imageafter45121.acAutoClean
      version: 1
      values: []
      patch: []
      exclusion: []
  actions:
    - component: main
      capability: temperatureMeasurement
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main
      capability: switch
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main
      capability: refresh
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main
      capability: imageafter45121.acTempSet
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main
      capability: imageafter45121.acWindLevel
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main
      capability: imageafter45121.acOpMode
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main
      capability: imageafter45121.acVolume
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main
      capability: imageafter45121.acOperation
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main
      capability: imageafter45121.acDirection
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main
      capability: imageafter45121.acCoMode
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main
      capability: imageafter45121.acAutoClean
      version: 1
      values: []
      patch: []
      exclusion: []
type: dth
mnmn: SmartThingsCommunity
vid: 0694508d-8d01-3e09-857c-ccba143c53b9
version: 0.0.1
presentationId: 0694508d-8d01-3e09-857c-ccba143c53b9
manufacturerName: SmartThingsCommunity
