---
dashboard:
  states:
    - label: "{{acAutoClean.value}}"
  actions: []
  basicPlus: []
detailView:
  - label: 자동 청소
    displayType: toggleSwitch
    toggleSwitch:
      command:
        name: 자동 청소
        off: Off
        on: On
      state:
        value: acAutoClean.value
        off: Off
        on: On
        label: 자동 청소
        alternatives:
          - key: Off
            value: 꺼짐
            type: inactive
          - key: On
            value: 켜짐
            type: active
automation:
  conditions:
    - label: 자동 청소
      displayType: list
      list:
        value: acAutoClean.value
        alternatives:
          - key: Off
            value: 꺼짐
          - key: On
            value: 켜짐
  actions:
    - label: 자동 청소
      displayType: list
      list:
        command: setAcAutoClean
        alternatives:
          - key: Off
            value: 꺼짐
          - key: On
            value: 켜짐
        supportedValues: supportedAcAutoCleans.value
id: imageafter45121.acAutoClean
version: 1