dashboard:
  states:
    - component: main
      capability: imageafter45121.acAutoClean
      version: 1
      values: []
      patch: []
  actions:
    - component: main
      capability: imageafter45121.acAutoClean
      version: 1
      values: []
      patch: []
detailView:
  - component: main
    capability: temperatureMeasurement
    version: 1
    values: []
    patch: []
  - component: main
    capability: switch
    version: 1
    values: []
    patch: []
  - component: main
    capability: refresh
    version: 1
    values: []
    patch: []
  - component: main
    capability: imageafter45121.acTempSet
    version: 1
    values: []
    patch: []
  - component: main
    capability: imageafter45121.acWindLevel
    version: 1
    values: []
    patch: []
  - component: main
    capability: imageafter45121.acOpMode
    version: 1
    values: []
    patch: []
  - component: main
    capability: imageafter45121.acVolume
    version: 1
    values: []
    patch: []
  - component: main
    capability: imageafter45121.acOperation
    version: 1
    values: []
    patch: []
  - component: main
    capability: imageafter45121.acDirection
    version: 1
    values: []
    patch: []
  - component: main
    capability: imageafter45121.acCoMode
    version: 1
    values: []
    patch: []
  - component: main
    capability: imageafter45121.acAutoClean
    version: 1
    values: []
    patch: []
automation:
  conditions:
    - component: main
      capability: temperatureMeasurement
      version: 1
      values: []
      patch: []
    - component: main
      capability: switch
      version: 1
      values: []
      patch: []
    - component: main
      capability: refresh
      version: 1
      values: []
      patch: []
    - component: main
      capability: imageafter45121.acTempSet
      version: 1
      values: []
      patch: []
    - component: main
      capability: imageafter45121.acWindLevel
      version: 1
      values: []
      patch: []
    - component: main
      capability: imageafter45121.acOpMode
      version: 1
      values: []
      patch: []
    - component: main
      capability: imageafter45121.acVolume
      version: 1
      values: []
      patch: []
    - component: main
      capability: imageafter45121.acOperation
      version: 1
      values: []
      patch: []
    - component: main
      capability: imageafter45121.acDirection
      version: 1
      values: []
      patch: []
    - component: main
      capability: imageafter45121.acCoMode
      version: 1
      values: []
      patch: []
    - component: main
      capability: imageafter45121.acAutoClean
      version: 1
      values: []
      patch: []
  actions:
    - component: main
      capability: temperatureMeasurement
      version: 1
      values: []
      patch: []
    - component: main
      capability: switch
      version: 1
      values: []
      patch: []
    - component: main
      capability: refresh
      version: 1
      values: []
      patch: []
    - component: main
      capability: imageafter45121.acTempSet
      version: 1
      values: []
      patch: []
    - component: main
      capability: imageafter45121.acWindLevel
      version: 1
      values: []
      patch: []
    - component: main
      capability: imageafter45121.acOpMode
      version: 1
      values: []
      patch: []
    - component: main
      capability: imageafter45121.acVolume
      version: 1
      values: []
      patch: []
    - component: main
      capability: imageafter45121.acOperation
      version: 1
      values: []
      patch: []
    - component: main
      capability: imageafter45121.acDirection
      version: 1
      values: []
      patch: []
    - component: main
      capability: imageafter45121.acCoMode
      version: 1
      values: []
      patch: []
    - component: main
      capability: imageafter45121.acAutoClean
      version: 1
      values: []
      patch: []
type: dth
presentationId: 7058efc0-258b-3f62-8500-062816ef1bf7
manufacturerName: SmartThingsCommunity
vid: 5b6aeb9d-e140-3614-9dd0-2e53b9b8e654
mnmn: SmartThingsCommunity
version: 0.0.1
