name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      working-directory: ./server
      run: go build -v

    - name: Test
      working-directory: ./server
      run: go test -v
    
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      working-directory: ./server
      with:
        name: artifact
        if-no-files-found: error 
